[package]
name = "solution-finder-port"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[workspace]

[dependencies]
sfinder-lib = { path = "sfinder-lib" }
